### PR TITLE
Update harbour-smpc-es.ts

### PR DESCRIPTION
**Pull request by GNUuser**

### CODE REVIEW

**Comment by GNUuser** [comment]
Hi ade
 Can you change the credit of spanish translator like GNUuser to carlosgonz please in openrepos. Thanks for the release.

**Comment by a-dekker** [comment]
Done!

**Comment by GNUuser** [comment]
Gracias Ade.

**Comment by GNUuser** [comment]
Ade the option to report issues in your SMPC fork is shutdown?

**Comment by a-dekker** [comment]
That's because of the fork I guess. It's enabled now.

**Comment by GNUuser** [comment]
Thank you, do you have paypal to support your Sailfish developments?

**Comment by a-dekker** [comment]
It's fine without donations, thanks.

**Pull request merged**
