### PR TITLE
[WIP] Refactoring

### PR DESCRIPTION
**Pull request by inta**
Hi Arno,

I started some work on this App some time ago. My idea was to change the whole UI to get a better fit with Jolla's rules for user interaction. I never had the time to finish it, but maybe it is easier done step by step instead of a one-shot change.

So what I did is refoctoring some things throughout the whole QML codebase. The next things on my list where:
- change translation to idbased (based on english as default and lines in code leads to more interruptions in my opionion)
- even more refactor the QML/Javascript and break out often reused parts to their own files/components
- last but not least, get rid of those tiles on the start/main page (that is not really Jolla-like, I think) and get some kind of new look and feel for this app

No offense intended though, the former authors did a great job creating this app.
I know this is a large bunch of changes and not ready for merging yet, but you might want to take a look at it and let me know if you want my help to bring this further along. I am a Javascript developer and quite firm with the QML basics, but I have no idea of C++. So sadly, I would not be able to help that much on the C++ part of the app.

### CODE REVIEW

**Comment by a-dekker** [comment]
Thanks @inta, I'll have a look at your changes on short notice!

**Comment by a-dekker** [comment]
The iconsize 512x512 is not used, I think I will leave that out.

p.s. and 256x256 is no longer required (it was required in the past).

**Comment by a-dekker** [comment]
The harbour folder within qml seems a bit odd to me. Never seen this structure and seems a bit redundant?

**Comment by a-dekker** [comment]
I've compiled you refactor branch version. Some thing I notice:

- Icon reference on About page is wrong, so it won't show up
- Pages like "Files" cannot be opened (FileBrowserPage.qml not found)
- Album page does not show up
-Cannot select artists (AlbumListDelegate is not a type)
-Stop button is the same size as the play button, although a bit overlapping.
- You are talking about changes to the tiles on the mainpage, but I do not notice any changes

Maybe I am doing something wrong or am I missing something?

**Comment by inta** [comment]
Icons:
Ok, the icon sizes where just taken from Jolla's app template.

qml/harbour:
That has it's source in a comment of some former developer who wanted to use imports by name and not folders. It seems like the file system structure is required by qmldir. That's nothing particularly important for me.

The rest:
Like I stated it's not ready, this is a work in progress and by no means complete. I did not even touch the tiles, that's just a todo what I would like to approach. Same thing for the idbased translations.

I could also break out some parts into smaller pull requests, or fix the issues here. I just wanted to get the changes/ideas out to you because it seems you want to develop this actively. I would love to help you with it if you like (though my time is currently somehow limited to the weekends).

**Comment by a-dekker** [comment]
I indeed misread it as stuff that was already implemented.

As I can not/will not merge this request in this state I will reject it.
If you want to contribute, please create small PR's on top of my most recent code, that addresses a single subject, and has no merge conflicts. Perhaps start with the stop button?

**Comment by inta** [comment]
Ok, can you please clarify which of my ideas you would like to see realised? Or give me some private channel where we can communicate about it?
I would only want to create new change requests that most likely will be merged. So the stop button will be the first thing I'll grab for my next spare time coding fun.

**Comment by a-dekker** [comment]
> Ok, can you please clarify which of my ideas you would like to see realised? Or give me some private channel where we can communicate about it?
> I would only want to create new change requests that most likely will be merged. So the stop button will be the first thing I'll grab for my next spare time coding fun.

You made your change to the stop button. What I did was just scale up the button on more highres devices, but the space between the buttons is not exactly equal. Your solution gave some button overlap though on my phone.
I do not have a clear goal in mind, but it sounds fine if you can provide a consistent, well scalable row of buttons. If you prefer to do some js optimization that also okay.

PR's are welcome, as long as it is not extremely bad coded or make the interface worse. Of course the latter is somewhat personal. I could always ask if it's okay to make some adjustments to the PR myself.

I'm on Telegram, so if more communication is inevitable we could op for that perhaps.

**Pull request closed without merging**
