### PR TITLE
translations loading fixed

### PR DESCRIPTION
**Pull request by inta**
Ok, translations are working again. If you do a debug build you will not be able to see it, you have to kill the debug connection and start the app from the launcher.

I did some other changes to the build process to get it in line with Jolla's recommendations. Config for the icons is much simpler now and for the build config the harbour-smpc.yaml file is used. If you want to make changes, do not touch the .spec file, change the .yaml and the Sailfish IDE will update the spec.

Revisiting translations was not that much fun, there were several duplicates I had to got through. Leave it like this now, but I saw Jolla is also recommending id based translations [over here](https://sailfishos.org/wiki/Internationalisation_and_Localisation).

### CODE REVIEW

**Comment by a-dekker** [comment]
I always remove the yaml file. I do not see any benefit in using it (and I know other developers do remove it), it's overhead and confusing in my opinion, why not edit/control the spec file directly? Unless you have a very good reason to keep it I'll remove it again.
As for some code formattng changes: I leave that to the qml formatter to decide, so I don't have to worry about that and forces a standard. It often breaks long lines into multiple lines.

Thanks for the pull request, if German translation looks good again and now with renewed buttons, it might be time for a new release with your credits!

**Comment by inta** [comment]
Well, as I said in the beginning I'm not that expierienced with Qt and for that reason I like to keep my stuff as close to "upstream" as possible. I just added the yaml because I took a Jolla app skeleton and applied it to this project. This is how I got the translations to work, so I thougt it is a good thing. I have no strong feelings about the yaml file.

And I do not care about credits at all. I want to contribute what I can and use the software on my own, so I am profiting as well. :)

I think we should get the french and spanish translations working before a release, shouldn't we? My french is more than dusty and I did never speek more than a few words of spanish, so I can not help much with that. But at least for spanish there is someone doing translations if I got that right.

**Comment by a-dekker** [comment]
I not sure who did the French translation and if he is still using this App. If someone is still interested in French I hope he/she steps forward in the future.
As for Spanish, it was a recent PR, but far from complete. The translator said he would redo it, but if and when I cannot tell. We could also opt for disabling those languages for now?

**Comment by inta** [comment]
I'm not sure what happens if they are active. I think the fallback would be english which should be ok. So if you like it, create a new release and other languages can be updated later.

**Comment by a-dekker** [comment]
Yes, strings that can not be translated will remain English.
I will make a few more minor changes. For example you removed the actual license from the spec file (you replaced it with LICENSE), but that's nitpicking.

**Comment by inta** [comment]
Yes, I noticed that, but I thought this is not a real change as its the file name for the license and inside it says its GPL. Thats just a change coming from the app template, not really intentional done...

**Comment by a-dekker** [comment]
Another small issue is that you removed the existing permission mask in the spec file, which leads to execute bits on for example images. It won't break the app, but files should only have execute bits when needed.

**Comment by inta** [comment]
You can take your time checking the PR and I'll fix such things in the future, so you don't have to fix it afterwards. But I think I do not have to touch the spec again, that was during fixing the translation config.

**Comment by a-dekker** [comment]
commit https://github.com/a-dekker/smpc/commit/0ad205493c7f8d2086e24a484923f7959c6c5530 might have broken some translation strings or added new ones.

**Pull request merged**
