### PR TITLE
Mainmenu

### PR DESCRIPTION
**Pull request by fuchsmich**
Rework of main page.
Added Button, but without function yet.

### CODE REVIEW

**Comment by a-dekker** [comment]
If we can't think of a killer function behind this new button we can always make it the "About" button.

**Comment by fuchsmich** [comment]
This, or "saved playlists" would be a good default.

**Comment by a-dekker** [comment]
Just tested on my tablet, about button works fine.

**Comment by fuchsmich** [comment]
I'm starting to transfer settings from c++ to qml.
Should I think about how to transfer settings from old to new location, or do we just tell the user to reconfigure his app? There's now easy solution for automatic transfer, which comes to my mind yet.

**Comment by a-dekker** [comment]
Are you talking about /home/nemo/.config/harbour-smpc/harbour-smpc.conf? That wouldn't need a new location would it?

**Comment by fuchsmich** [comment]
That's the location, which qt uses natively. But Sailfish uses [dconf](https://sailfishos.org/develop/docs/nemo-qml-plugin-configuration/), which wasn't available back then.
I'd like to use the new approach, because it's much easier to maintain.

**Comment by a-dekker** [comment]
As far as I remember dconf was available from the beginning, but I think you are talking about the import of Nemo.Configuration in qml.

I still use the conf file most of the time in qml. For that, I use a simple wrapper, see for example https://github.com/a-dekker/acid-pass/blob/master/src/settings.cpp

The use is pretty much like in c++: https://github.com/a-dekker/acid-pass/blob/master/qml/pages/PasswordPage.qml#L32

That would avoid the need for migration settings, but if you are strongly in favor of dconf settings I wouldn't mind.

**Comment by fuchsmich** [comment]
I like the implementation of Nemo.Configuration.
You bind the value to a property 
    
    someProperty: settings.value

and somewhere else in the app you change the setting

    settings.value = "cooool"

and `settings.value` gets saved and `someProperty` is updated as well.

**Comment by fuchsmich** [comment]
I guess you are right, we should stay with QSettings.

**Comment by a-dekker** [comment]
Will close this, as parts of this pull request are merged and further development on this draft is stopped.

**Pull request closed without merging**
