### PR TITLE
currentplaylist trackdelegate

### PR DESCRIPTION
**Pull request by fuchsmich**
I couldn't test "Add to saved playlist" here.

### CODE REVIEW

**Comment by a-dekker** [comment]
Is this related to the "show artist" issue I mentioned yesterday?
I would like to have a "no regressions" situation first, then make a new release before moving on other changes.

**Comment by fuchsmich** [comment]
> Is this related to the "show artist" issue I mentioned yesterday?
Yes, absolutely.

I reverted some of my changes for this and simplified some code. 
I also discovered, that "Play as next" had a bug introduced by me.

But I can't test saved playlists at my current computer.

**Comment by a-dekker** [comment]
Good to know, I will see if I can test "add to saved playlist".

**Comment by a-dekker** [comment]
Add to save playlists seems to work file.
Only thing I notice is this message on the console:

`[W] unknown:207 - file:///usr/share/harbour-smpc/qml/pages/database/PlaylistTracksPage.qml:207: ReferenceError: clearPlaylistTracks is not defined`

**Comment by fuchsmich** [comment]
I search for `clearPlaylistTracks` (also in old code), but couldn't find the function referenced here. So this error maybe already existed for a long time. It does not harm, but I will comment it out.

**Comment by a-dekker** [comment]
That's most likely the case than.

**Pull request merged**
