### PR TITLE
scalable stop button and for light and dark ambiences

### PR DESCRIPTION
**Pull request by inta**
I moved the play/pause, stop, etc. controls to a separate component  and reworked some of the properties not needed on global level (main.qml).

I removed some of the qml files from harbour-smpc.pro and added a QML_IMPORT_PATH instead, because QML files where spread around different folders in the IDE's file tree. QML files still appear under Sources in the Sailfish IDE, because of the lupdate_only part in the pro file. I think that has to be removed to get it all working well. I did not do it right now, because translations seem to be not working at all. I installed SMPC from OpenRepos, but its the same there, I get an english UI although german translations should be available. So I did not commit the changed language files. Can you please have a look at the translations? Is it working anywhere? Any idea what needs to be done to get it working?

### CODE REVIEW

**Comment by a-dekker** [comment]
_About the translations_
the transition to a capital first letter sadly broke a lot of translation strings (as 'hello there' != 'Hello there')
I did a quick attempt to fix that by some magic commands, but that did not work on short term.
The second change is that I moved the translation files to the normally default location (translations/) and added an (incomplete) Spanish translation.

So the old translation needs to be converted to uppercase, or strings have to be re-translated.

**Comment by inta** [comment]
Ok, so let me know if I should do some work on the translation problem, or if there is something more to do regarding this PR.

**Comment by a-dekker** [comment]
If you could fix the German translation, please do. The old translation (harbour-smpc_de.ts) from before the change could be a good guideline. A tool like Qt5 Linguist is my preferred way of making translations. It's quite a lot of translatable text for a sailfish app.

Meanwhile I am facing issues with Virtualbox and a more recent kernel, so I can't fire up the Sailfish IDE right now. Will have to sort that out first.

**Comment by inta** [comment]
I'll have a look at it later. Do you want to leave it as "normal" translations or are you ok if I try to switch them to idbased? The idbased do not have the line of the source file in them, so you can change source code without changing tanslations. I think that is more robust, but may be even more work to do for the switching.

Oh, I got through the Virtualbox switch some weeks ago. Are you using some Debian based distribution and using the official Virtualbox repo? You'll have to create a signing key for kernel modules and sign them after a reboot. I followed [this guide](https://gist.github.com/reillysiemens/ac6bea1e6c7684d62f544bd79b2182a4) which works great, but is for Fedora so you have to adapt some changes for Debian. If you need help, I think I have the changed scripts lying around.

**Comment by a-dekker** [comment]
I do not have experience with id-based translations. It will have is advantages and disadvantages.

I'm running OpenSUSE tumbleweed. This means I always have the latest and greatest, but sometimes things break if Virtualbox does not support the latest kernel changes yet.

**Comment by a-dekker** [comment]
Latest VirtualBox development build works!

**Comment by inta** [comment]
Great, I thought you got the "secure boot issue", but anyways great it is solved.

Sure id based has the disadvantage, that the translation key is not always self-explaining. It looks something like "playback.button.stop.label" or however you might call it. So you might need to add some special translation comments so make it easier for the translators. I do not know about other drawbacks.

I just saw the line numbers switching every time I changed some code blocks and thought that this is not really helpful when you want to refactor larger parts of the code base. But I am not that familiar with linguist and do not know how it handles such changes.

**Comment by a-dekker** [comment]
The original author made the play button bigger than the rest of the buttons (just like in the Talefish app). But the bigger stop button looks excellent here in my opinion. Thank you!

**Comment by a-dekker** [comment]
If configured, the translation files are updated during a build. So if you insert code, line numbers will shift. In most cases, it is fixed by itself once compiled again.

**Comment by inta** [comment]
Ok, I'll test it later with the german translation and if it works I'll create a pull request.

**Pull request merged**
