### PR TITLE
mpd V.<021 empty Album List bug - pushUp Play added Position slider

### PR DESCRIPTION
**Pull request by sh6668**
Hi
patch for Bug with old mpd <0.21 (like in volumio)
Album List was empty
and
added position slider to pushUp ControlPanel
(because i like it there...)

### CODE REVIEW

**Comment by a-dekker** [comment]
Thanks for your PR. I assume there was an issue with old mpd versions, I usually work with more recent versions.

I am a bit in doubt about the ControlPanel change. It already was quite a big surface, this make makes it cover the entire screen in landscape.
There where discussions before where to place new functionality. that's why I placed options like Consume track and single playback in the playback settings in the end and not in the panel.

Maybe we could go for a setting: show volume or position? Personally I never use volume, but control this on the playing device itself.

**Comment by a-dekker** [comment]
Having two separate PR's for two different issues would also have been more convenient.

**Comment by sh6668** [comment]
Yes, should be separated. Please ignore the position part.
(On my xperia 10 it's nice:-))
Your idea with settings is the right way. 
In guiSetting one TextSwitch for Show Position Slider
and one for Show Volume Slider, defaults Vol yes and Pos no?

**Comment by a-dekker** [comment]
Sound like a good idea to me!

Then I'll merge this request and remove the qml change part for now.

**Pull request merged**
