### PR TITLE
Newcontroller

### PR DESCRIPTION
**Pull request by fuchsmich**
For your info: I started a rewrite of the c++ part. All the signals and slots (the communication between c++ and qml) will be moved or renamed.
Therefore a need to rename them in qml. During this process I also started to reorganize the qml components. (see VolumeSlider or ProgressBar).
I'm also finding (and removing) some code, which is not used anymore.

### CODE REVIEW

**Comment by fuchsmich** [comment]
I will try to finish the code, which handles playback (play/pause, seek, volume, etc) and the playlist (add to/remove from playlist, etc). And then we can merge this part.

**Comment by a-dekker** [comment]
It seems the newcontroller branch is based on an old codebase, as all kind of old UI stuff reappears after compiling?

**Comment by fuchsmich** [comment]
For example?
Here it looks fine. The branch `newcontroller` is based on your `master` branch. Would be horrible, if this doesn't work.

**Comment by a-dekker** [comment]
Sorry, false alarm. Somehow this branch in my local repo was not up-to-date. Now it looks just fine.

**Comment by fuchsmich** [comment]
... phew ...

**Comment by a-dekker** [comment]
Currently the pulley menu is missing when I select an album? Makes playing an album difficult.

**Comment by fuchsmich** [comment]
Thanks for the hint, should be working again.

**Comment by fuchsmich** [comment]
Switches are invisible and just for demo. Icons have to be changed.

**Comment by a-dekker** [comment]
> Switches are invisible and just for demo. Icons have to be changed.

It breaks the app at the moment, right?

**Comment by fuchsmich** [comment]
break? how? what?

But anyway, I'll put it in a different branch.

**Comment by a-dekker** [comment]
> break? how? what?
> 
> But anyway, I'll put it in a different branch.
Got this after a git pull and compile (white screen):
```
[W] unknown:264 - file:///usr/share/harbour-smpc/qml/main.qml:264:5: Type ControlPanel unavailable 
         ControlPanel { 
         ^
[W] unknown:98 - file:///usr/share/harbour-smpc/qml/components/ControlPanel.qml:98:9: Type PlaybackControls unavailable 
             PlaybackControls {} 
             ^
[W] unknown:64 - file:///usr/share/harbour-smpc/qml/components/PlaybackControls.qml:64:5: SingleSwitch is not a type 
         SingleSwitch { 
         ^
```

**Comment by a-dekker** [comment]
How is this part progressing? Do you still want to make additional changes, or do you want me to (try) to review it and merge it?

**Comment by fuchsmich** [comment]
:grimacing: hmmm, I'm sorry. I don't know what to do right now. I'm afraid the best way would be to break everything and start reimplementing every functionality step by step.
It's very hard to keep the app intact while rewriting the communication with mpd and the qml-interface.

I will think about this till Sunday. Maybe it's a better option to start a devel branch.

My aims are:

- keep the look and feel of the app
- copy modern c++ and qml technics from cantata and musikilo
- organize commonly used components (as said above)
- and keep in mind the revive of daedalus

**Comment by fuchsmich** [comment]
Ok, I think I'll continue the current way of small steps and publish them soon. It's more motivating.
This branch is now in a state, which *should* be working. So you can test it and then we can merge it into master. 

I don't know, if you want to release it as well, because there is no change for user right now.

**Comment by a-dekker** [comment]
That's sound fine to me, staying motivated is the key ingredient :-). I have some small UI changes I want to make, so I could include that in a new release.

**Comment by a-dekker** [comment]
Adding files seems broken now:

`unknown:43 - file:///usr/share/harbour-smpc/qml/pages/database/FileBrowserPage.qml:43: TypeError: Property 'addFiles' of object Playlist(0xb5abd90) is not a function`

**Comment by fuchsmich** [comment]
Great. Do you think I should make this one big commit?

**Comment by a-dekker** [comment]
Yes, I already merged it. Too bad I encountered this "add files" regression later on.
If you could have a look at it and create a small PR for that if possible.

**Comment by a-dekker** [comment]
It looks something else went wrong in some of the last commits: the now playing detail page no longer shows the artist and cover image.

**Comment by fuchsmich** [comment]
addFiles is fixed.

> the now playing detail page no longer shows the artist and cover image.

Do you mean `CurrentSong.qml`? The Artistname shows up for me, but artwork doesn't.

**Comment by a-dekker** [comment]
I do miss the cover-art and artist image (so artwork I guess). Normally they swap at an interval, but both images are not displayed atm.

**Comment by fuchsmich** [comment]
Ok, I guess this takes some more time. I don't know much yet about the image code.

**Comment by a-dekker** [comment]
I am afraid I found another regression: selecting "Show artist" from a number of a playlist should show al related albums from the artist. But it does not show anything now.

**Comment by a-dekker** [comment]
I can't detect any regressions still present. So I added some small changes by myself and made a new release on Openrepos.

**Comment by a-dekker** [comment]
> My aims are:
> 
>     * keep the look and feel of the app
> 
>     * copy modern c++ and qml technics from cantata and musikilo
> 
>     * organize commonly used components (as said above)
> 
>     * and keep in mind the revive of daedalus

Side question: what would be so interesting about reviving Daedalus? There are quite a few local music players nowadays. Would installing MPD with SMPC as a client not be much easier and save the hassle of maintaining two apps?

**Comment by fuchsmich** [comment]
Good question. I just like the interface of SMPC. But since @haasn talked about his config in #34 I'm also thinking about installing mpd locally.

**Comment by fuchsmich** [comment]
...but keeping portability in mind is always good, as it keeps the code cleaner IMO. Another idea is making a fork/version with kirigami (qtquick controls 2) interface (for other mobile OSes ubports, mobian, etc.).

**Comment by a-dekker** [comment]
I also compiled and installed the latest MPD version on my device, and enabled socket activation. Works fine.

**Pull request merged**
